---
- name: Playbook for patching the servers
  hosts: worker_nodes
  become: yes
  ignore_errors: no
  gather_facts: yes
  serial: 1

  tasks:
    - name: Checking whether space available or not for update
      set_fact:
        root_mount: "{{ ansible_mounts | selectattr('mount','equalto','/') | first }}"
      tags: space_status

    - name: Stop if insufficient space
      fail:
        msg: 
          " The available space is
          {{ (root_mount.size_available/1024**3) | round(2) }} GB
          atleast 2GB is required "
      when: root_mount.size_available < (2 * 1024 * 1024 * 1024 )
      tags: space_status

    - name: Patching rhel servers
      dnf:
        name: "*"
        bugfix: true
        security: true
        skip_broken: true
        update_cache: true
        state: latest
      when: ansible_distribution == "RedHat"
      tags: patching

    - name: Patching ubuntu servers
      apt:
        update_cache: true
        upgrade: full
      when: ansible_distribution == "Ubuntu"
      tags: patching
...
